import fs from 'node:fs'
import react from '@vitejs/plugin-react'
import { defineConfig, loadEnv } from 'vite'
import { handleEarlyAccess } from './server/earlyAccess.js'

// Inline the self-hosted @font-face rules (public/fonts/fonts.css, generated by
// scripts/fetch-fonts.mjs from the exact Google Fonts URL the Webflow export used) into <head>:
// no render-blocking third-party stylesheet, same font binaries.
function inlineFonts() {
  return {
    name: 'foreshift:inline-fonts',
    transformIndexHtml(html) {
      const css = fs.readFileSync(new URL('./public/fonts/fonts.css', import.meta.url), 'utf8').trim()
      return html.replace('<!--fonts-->', `<style>${css}</style>`)
    },
  }
}

function earlyAccessApi() {
  return {
    name: 'foreshift:early-access-api',
    configureServer(server) {
      const env = loadEnv(server.config.mode, process.cwd(), '')
      server.middlewares.use(async (req, res, next) => {
        const url = req.url?.split('?')[0]
        if (url !== '/api/early-access') return next()
        if (req.method !== 'POST') {
          res.statusCode = 405
          res.setHeader('Allow', 'POST')
          res.setHeader('Content-Type', 'application/json')
          res.end(JSON.stringify({ error: 'Method not allowed' }))
          return
        }
        const chunks = []
        for await (const chunk of req) chunks.push(chunk)
        let body
        try {
          const raw = Buffer.concat(chunks).toString('utf8')
          body = raw ? JSON.parse(raw) : {}
        } catch {
          res.statusCode = 400
          res.setHeader('Content-Type', 'application/json')
          res.end(JSON.stringify({ error: 'Invalid JSON' }))
          return
        }
        const result = await handleEarlyAccess(body, { ...process.env, ...env })
        res.statusCode = result.status
        res.setHeader('Content-Type', 'application/json')
        res.end(JSON.stringify(result.body))
      })
    },
  }
}

// https://vite.dev/config/
export default defineConfig({
  plugins: [react(), inlineFonts(), earlyAccessApi()],
  build: {
    // manifest is consumed (then deleted) by scripts/prerender.mjs for per-route modulepreloads.
    manifest: true,
    sourcemap: false,
  },
})
