import fs from 'node:fs'
import react from '@vitejs/plugin-react'
import { defineConfig } from 'vite'

// Inline the self-hosted @font-face rules (public/fonts/fonts.css, generated by
// scripts/fetch-fonts.mjs from the exact Google Fonts URL the Webflow export used) into <head>:
// no render-blocking third-party stylesheet, same font binaries.
function inlineFonts() {
  return {
    name: 'foreshift:inline-fonts',
    transformIndexHtml(html) {
      const css = fs.readFileSync(new URL('./public/fonts/fonts.css', import.meta.url), 'utf8').trim()
      return html.replace('<!--fonts-->', `<style>${css}</style>`)
    },
  }
}

// https://vite.dev/config/
export default defineConfig({
  plugins: [react(), inlineFonts()],
  build: {
    // manifest is consumed (then deleted) by scripts/prerender.mjs for per-route modulepreloads.
    manifest: true,
    sourcemap: false,
  },
})
